"""rename summary to profile_summary in analyses

Revision ID: 02dd7b7c87a1
Revises: 8360faa5763b
Create Date: 2026-06-14 19:54:04.087697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '02dd7b7c87a1'
down_revision: Union[str, Sequence[str], None] = '8360faa5763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('profile_summary', sa.Text(), nullable=True))
    op.drop_column('analyses', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('summary', mysql.TEXT(), nullable=True))
    op.drop_column('analyses', 'profile_summary')
    # ### end Alembic commands ###
