"""add display fields to analyses

Revision ID: b70956063ed8
Revises: 798f98c55f0e
Create Date: 2026-06-20 02:19:37.131105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70956063ed8'
down_revision: Union[str, Sequence[str], None] = '798f98c55f0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('profile_name', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('profile_headline', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('profile_location', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('profile_picture', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('follower_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'follower_count')
    op.drop_column('analyses', 'profile_picture')
    op.drop_column('analyses', 'profile_location')
    op.drop_column('analyses', 'profile_headline')
    op.drop_column('analyses', 'profile_name')
    # ### end Alembic commands ###
